name: Generar Changelog en PR a Integration

on:
  pull_request:
    branches: [ integration ]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generar Changelog
        run: conventional-changelog -i CHANGELOG.md -s -r 0